// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {menu} from '../models';

export function AddTask(arg1:string):Promise<utils.Response>;

export function DeleteTask(arg1:string):Promise<utils.Response>;

export function FilterTasks(arg1:string):Promise<utils.Response>;

export function GetSettingList():Promise<utils.Response>;

export function GetTaskList():Promise<utils.Response>;

export function Greet(arg1:string):Promise<string>;

export function Menu():Promise<menu.Menu>;

export function UpdateSettingList(arg1:any):Promise<utils.Response>;

export function UpdateTask(arg1:string):Promise<utils.Response>;
