// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1) {
  return window['go']['app']['App']['AddSource'](arg1);
}

export function AddTask(arg1) {
  return window['go']['app']['App']['AddTask'](arg1);
}

export function CheckSourceList() {
  return window['go']['app']['App']['CheckSourceList']();
}

export function DelSource(arg1) {
  return window['go']['app']['App']['DelSource'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['app']['App']['DeleteTask'](arg1);
}

export function EditSource(arg1) {
  return window['go']['app']['App']['EditSource'](arg1);
}

export function FilterTasks(arg1) {
  return window['go']['app']['App']['FilterTasks'](arg1);
}

export function GetSettingList() {
  return window['go']['app']['App']['GetSettingList']();
}

export function GetSourceList() {
  return window['go']['app']['App']['GetSourceList']();
}

export function GetTaskList() {
  return window['go']['app']['App']['GetTaskList']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function Menu() {
  return window['go']['app']['App']['Menu']();
}

export function SearchCourse(arg1) {
  return window['go']['app']['App']['SearchCourse'](arg1);
}

export function UpdateSettingList(arg1) {
  return window['go']['app']['App']['UpdateSettingList'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['app']['App']['UpdateTask'](arg1);
}
